### ISSUE TITLE
cannot load such file -- /usr/local/share/gems/gems/rush2-0.8.0/lib/rush/path (LoadError)

### ISSUE THREAD

**Issue by electricface** [s-mage/rush#17]
/usr/local/share/gems/gems/rush2-0.8.0/lib/rush/string_ext.rb:1:in `require_relative': cannot load such file -- /usr/local/share/gems/gems/rush2-0.8.0/lib/rush/path (LoadError)
        from /usr/local/share/gems/gems/rush2-0.8.0/lib/rush/string_ext.rb:1:in `<top (required)>'
        from /usr/local/share/gems/gems/rush2-0.8.0/lib/rush.rb:83:in `require_relative'
        from /usr/local/share/gems/gems/rush2-0.8.0/lib/rush.rb:83:in `<top (required)>'
        from /usr/local/share/gems/gems/rush2-0.8.0/bin/rush:3:in `require_relative'
        from /usr/local/share/gems/gems/rush2-0.8.0/bin/rush:3:in `<top (required)>'
        from /usr/local/bin/rush:23:in `load'
        from /usr/local/bin/rush:23:in `<main>'

**Comment by s-mage** [comment]
On Sunday, November 08, 2015 05:31:56 PM electricface wrote:
> /usr/local/share/gems/gems/rush2-0.8.0/lib/rush/string_ext.rb:1:in
> `require_relative': cannot load such file --
> /usr/local/share/gems/gems/rush2-0.8.0/lib/rush/path (LoadError) from
> /usr/local/share/gems/gems/rush2-0.8.0/lib/rush/string_ext.rb:1:in `<top
> (required)>' from /usr/local/share/gems/gems/rush2-0.8.0/lib/rush.rb:83:in
> `require_relative' from
> /usr/local/share/gems/gems/rush2-0.8.0/lib/rush.rb:83:in `<top (required)>'
> from /usr/local/share/gems/gems/rush2-0.8.0/bin/rush:3:in
> `require_relative' from
> /usr/local/share/gems/gems/rush2-0.8.0/bin/rush:3:in `<top (required)>'
> from /usr/local/bin/rush:23:in `load'
>         from /usr/local/bin/rush:23:in `<main>'
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/s-mage/rush/issues/17

I'll check in the evening, for now please try rush right from the repo

**Comment by s-mage** [comment]
Just released v0.9. @electricface please check.
